### PR TITLE
Added support for ida 7.0

### LINKED ISSUE #4: Error IDA 7
Hi, The plugin fails to start in IDA Version 7. Works perfectly in v6.95.
"
Failed while executing plugin_t.init():
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/x64dbgida.py", line 206, in init
    menu = idaapi.add_menu_item("Edit/x64dbgida/", "About", "", 0,
AttributeError: 'module' object has no attribute 'add_menu_item'
"

### PR DESCRIPTION
**Pull request by techbliss**
I tested it on  IDA PRO  6.6, 6.8, 6.95, and 7.0.

closes #4

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks!
